# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Basys-3-Master.xdc

# Block Designs: bd/Main_System/Main_System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_System || ORIG_REF_NAME==Main_System} -quiet] -quiet

# IP: bd/Main_System/ip/Main_System_v_axi4s_vid_out_0_0/Main_System_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_System_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==Main_System_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/Main_System/ip/Main_System_v_tc_0_0/Main_System_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_System_v_tc_0_0 || ORIG_REF_NAME==Main_System_v_tc_0_0} -quiet] -quiet

# IP: bd/Main_System/ip/Main_System_v_tpg_0_0/Main_System_v_tpg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_System_v_tpg_0_0 || ORIG_REF_NAME==Main_System_v_tpg_0_0} -quiet] -quiet

# IP: bd/Main_System/ip/Main_System_vga_trunc_0_0/Main_System_vga_trunc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_System_vga_trunc_0_0 || ORIG_REF_NAME==Main_System_vga_trunc_0_0} -quiet] -quiet

# IP: bd/Main_System/ip/Main_System_xlconstant_0_0/Main_System_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_System_xlconstant_0_0 || ORIG_REF_NAME==Main_System_xlconstant_0_0} -quiet] -quiet

# IP: bd/Main_System/ip/Main_System_clk_wiz_0_0/Main_System_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_System_clk_wiz_0_0 || ORIG_REF_NAME==Main_System_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/Main_System/Main_System_ooc.xdc
