# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado/Projekt_UEC/Projekt_UEC.cache/wt [current_project]
set_property parent.project_path D:/vivado/Projekt_UEC/Projekt_UEC.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo d:/vivado/Projekt_UEC/Projekt_UEC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/new/GPU.v
  D:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/new/font_rom.v
  D:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/new/gpu_block.v
  D:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/new/gpu_debuger.v
  D:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/new/gpu_frame.v
  D:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/new/gpu_text.v
  D:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/new/gpu_timing.v
  D:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/new/texture_rom.v
  D:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/new/CPU.v
}
read_ip -quiet D:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/Projekt_UEC/Projekt_UEC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/Projekt_UEC/Projekt_UEC.srcs/constrs_1/imports/src/constraint.xdc
set_property used_in_implementation false [get_files D:/vivado/Projekt_UEC/Projekt_UEC.srcs/constrs_1/imports/src/constraint.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CPU -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
